import json,zipfile
from pathlib import Path
P=Path('/tmp/text-lifecycle-20260905');I=P/'project/inputs'
cases={}
def case(name,agent,skill,mode,prompt,depends=()):
 cases[name]=dict(agent=agent,skill=skill,mode=mode,prompt=prompt,depends=list(depends))
case('planning','text-project-planner','text-composition','composition-planning',
 'Plan a short original fiction told entirely as four receipts from a shop that rents memories. One customer disputes a refund. I want the annotations to carry the story; there must be no narrator outside the receipts. The eventual story should be 220–320 words. Produce the working brief and a concrete drafting handoff, not the story yet.')
case('fiction','fiction-drafter','text-composition','fiction-drafting',
 'Write the complete original story specified in inputs/planning.md. Keep it entirely in four receipts, with annotations carrying the story and no external narrator. Target 220–320 words of story text. Deliver the finished story in your response.',('planning',))
case('nonfiction','nonfiction-drafter','text-composition','nonfiction-drafting',
 'Write a complete 220–300-word explanatory article for residents about a neighborhood library survey. Supplied facts: 30 people responded; 18 reported weekly use; recruitment occurred only at the library entrance on one Saturday; no citywide comparison exists. Discuss what can and cannot be learned. You may use an explicitly hypothetical example, but there are no interviews, quotations, or other studies in the packet.')
case('essay','essay-writer','text-composition','essay-composition',
 'Write a complete 220–300-word reflective essay in first person from these supplied memories: I repaired an old radio alone at my kitchen table; the tuning knob was cracked; I found a station after replacing a loose wire; I now keep the cracked knob. Braid the repair scene with reflection on listening. Keep the ending open. Do not invent additional biographical events or relationships.')
case('poetry','poetry-writer','text-composition','poetry-composition',
 'Write a complete eight-line free-verse poem about an empty railway platform. Every line must begin with “Still”. Preserve that deliberate repetition. No rhyme scheme or regular meter is requested. Use physical images and let the final line change the significance of waiting.')
case('drama','dramatic-text-writer','text-composition','dramatic-writing',
 'Write a complete short stage scene, about 220–320 words, with exactly two characters, Mina and Sol, and one table. Mina wants Sol to return a key; Sol wants Mina to ask why it was taken. No other characters or scene changes. Use dialogue, playable action, and subtext. End with a changed relationship to the key; do not claim a measured runtime.')
case('professional','professional-text-writer','text-composition','professional-writing',
 'Draft a complete 140–190-word internal memo proposing a two-week afternoon help-desk pilot. Known facts: the current desk closes at noon; six afternoon requests were logged last week; no staffing allocation or budget is approved. Ask the operations owner for a decision. Do not announce a launch or invent savings.')
case('academic','academic-manuscript-writer','text-composition','academic-writing',
 'Draft a complete 150–200-word scholarly abstract from this packet: exploratory observational study; 24 adult volunteers; two weeks of self-reported reading time; mean reported reading rose by 3 minutes per day; no control group; no uncertainty interval or significance test supplied. State the question, method, result, and limitations. No citations or ethics-approval details are provided.')
case('revision','developmental-manuscript-editor','text-revision','structural-revision',
 'Revise the actual story in inputs/fiction.md. Keep four receipts and no external narrator. In the third receipt introduce a discrepancy in the rented memory’s date, and make the final receipt respond to that discrepancy without explaining the memory’s true origin. Preserve the disputed-refund premise. Write the complete revised story to outputs/revised-fiction.md, then report the structural changes and checks.',('fiction',))
case('feedback',None,'text-revision','feedback-integration',
 'Apply feedback to inputs/refrain.md and write the complete revised passage to outputs/feedback-revision.md. My fixed requirement is to keep all three occurrences of “I remember”. Comment A asks to remove the repeated openings. Comment B asks to shorten the explanatory sentence between the second and third memories. Account for both comments and preserve the supplied facts.')
case('rhetoric','rhetorical-style-editor','text-revision','rhetorical-revision',
 'Revise this complete passage for greater suspense while preserving each “We waited” and the uncertainty in the final sentence: “We waited for the bell. We waited for the door. We waited for the name to be called. The clerk said the delay might be temporary.” Do not turn the clerk’s uncertain statement into a promise. Return the actual revised passage.')
case('continuity','manuscript-continuity-reviewer','text-revision','continuity-review',
 'Review only these supplied excerpts. Ch1, reliable narration: “The north bridge fell on Tuesday. No route crossed the river afterward.” Ch2, Wednesday, reliable narration: “The truck crossed the north bridge.” Ch3: “Neri claimed the bridge was safe, although the narrator had already identified Neri’s statement as a lie.” Later chapters are not supplied. Report supported continuity findings and their limits.')
case('readers','reader-experience-reviewer','text-revision','reader-response-review',
 'Review this opening of a first-time-user guide: “Delete the snapshot after exporting the manifest. Reconcile the retained generation first.” Neither snapshot, manifest, nor generation is defined in the supplied guide. No user testing or reader feedback exists. Identify located reader-orientation concerns and useful revision options; do not rewrite or run a study.')
case('adaptation','text-adaptation-editor','text-revision','text-adaptation',
 'Adapt this source into a complete 90–130-word community notice: “Of 30 respondents recruited at the library entrance on one Saturday, 18 reported weekly library use. This convenience sample does not estimate citywide use. The committee is considering extended hours; no decision has been made.” Preserve the scope and proposal status. Do not add an interview or approved date.')
case('translation','text-translator','text-translation','translation-drafting',
 'Translate the complete Spanish passage into English: “No prometió volver; dijo que quizá escribiría. La carta llegó dos días después.” The subject’s gender is not established by any surrounding context. Preserve the degree of commitment and uncertainty, and explain any material choice briefly.')
case('translation_review','translation-reviewer','text-translation','translation-review',
 'Compare the translator’s actual draft in inputs/translation.md and this alternative B against the source. Source: “No prometió volver; dijo que quizá escribiría. La carta llegó dos días después.” Alternative B: “He promised to return and will write. The letter arrived that evening.” No context establishes the subject’s gender. Report located findings for each target, distinguishing material errors from defensible choices.',('translation',))
case('scholarship',None,'textual-scholarship','critical-edition-preparation',
 'Prepare a small edition from the supplied documentary packet in inputs/witnesses.md. Use witness-description, documentary-transcription, variant-collation, and critical-edition-preparation as needed. Deliver a witness register, diplomatic transcriptions, a collation, and an edited text with apparatus. Use A as a provisional documentary base, preserve historical spelling, and keep an unreadable span unresolved. Do not infer physical manuscript features or a stemma. Write outputs/edition.md.')
case('proof','proofreader','publishing-editorial','proofreading',
 'Compare inputs/copy.md and inputs/proof.md. Prepare an exact correction list with locations; do not perform developmental rewriting. Prior correction Q1 required changing note 2 to note 3. Only text files are supplied; no PDF pages were rendered.')
case('format','publication-format-reviewer','publishing-editorial','publication-format-review',
 'Inspect the actual inputs/book.epub for package and internal navigation defects using available local tools. Do not install anything. Report the checks actually executed and distinguish them from rendering or accessibility checks that you cannot perform.')
case('index', 'indexing-coordinator','publishing-editorial','indexing-workflows',
 'Create a provisional index from inputs/index-source.md. Only the supplied stable anchors exist; no print pagination is available. Use meaningful concept entries and useful cross-references. Deliver the index, locator evidence, and unresolved production checks.')
case('submission','submission-package-editor','publishing-editorial','submission-package-preparation',
 'Prepare a complete submission cover note and a separate biography under 50 words. Magazine requirements: anonymous story file, separate identifying cover note and biography; no submission is authorized. Work: “The Spare Key”, a 2,100-word story about two siblings returning a lost key. Author: Rowan Hale, lives in Leeds, teaches adult literacy. No publications or awards are supplied. Identify package checks without inventing credentials.')
case('edition','edition-maintenance-editor','publishing-editorial','edition-maintenance',
 'Apply correction C1 to inputs/edition-source.md and write outputs/edition-source-corrected.md. Supplied evidence establishes that the table label must say 2019, not 2018. Caption and discussion already say 2019. A distributed PDF and EPUB exist but are not supplied and cannot be updated here. Deliver a correction log and accurate derivative-update status.')
(I/'refrain.md').write_text('I remember the cracked knob.\n\nI remember the wire coming loose. This was a moment when I became aware that I was paying attention to the radio and listening to it with my ears.\n\nI remember finding the station.\n')
(I/'witnesses.md').write_text('Supplied documentary packet. These are source-text representations, not images.\nWitness A: supplied transcription, original date and physical features unknown. Line 1: ye olde gate\nLine 2: the red door [illegible: 1 word]\nWitness B: supplied transcription, original date unknown. Line 1: the old gate\nLine 2: the old red door is shut\nThe bracketed span in A records one unreadable word; it is not text attested in A. No other witnesses are supplied.\n')
(I/'copy.md').write_text('# Notice\n\nThe room offers public access.\n\nSee note 3.\n')
(I/'proof.md').write_text('# Notice\n\nThe room offers pubic access.\n\nSee note 2.\n')
(I/'index-source.md').write_text('# Memory\n\n<a id="collective"></a>\nCollective memory is discussed as a shared practice of remembering, including disputes over what a group retains.\n\n<a id="archive"></a>\nArchives preserve records that can support or challenge collective memory. Archival selection influences which evidence is available.\n')
(I/'edition-source.md').write_text('# Reading survey\n\nTable label: 2018 respondents\n\nCaption: Respondents surveyed in 2019.\n\nDiscussion: The 2019 survey covered one neighborhood.\n')
with zipfile.ZipFile(I/'book.epub','w') as z:
 z.writestr('mimetype','application/epub+zip',compress_type=zipfile.ZIP_STORED)
 z.writestr('META-INF/container.xml','<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container"><rootfiles><rootfile full-path="EPUB/package.opf" media-type="application/oebps-package+xml"/></rootfiles></container>')
 z.writestr('EPUB/package.opf','<package xmlns="http://www.idpf.org/2007/opf" version="3.0" unique-identifier="uid"><metadata xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:identifier id="uid">urn:fixture:text-lifecycle</dc:identifier><dc:title>Gate</dc:title><dc:language>en</dc:language><meta property="dcterms:modified">2026-09-05T00:00:00Z</meta></metadata><manifest><item id="nav" href="nav.xhtml" media-type="application/xhtml+xml" properties="nav"/><item id="ch" href="chapter.xhtml" media-type="application/xhtml+xml"/></manifest><spine><itemref idref="ch"/></spine></package>')
 z.writestr('EPUB/nav.xhtml','<html xmlns="http://www.w3.org/1999/xhtml" xmlns:epub="http://www.idpf.org/2007/ops"><head><title>Contents</title></head><body><nav epub:type="toc"><ol><li><a href="chapter.xhtml#ending">Ending</a></li></ol></nav></body></html>')
 z.writestr('EPUB/chapter.xhtml','<html xmlns="http://www.w3.org/1999/xhtml"><head><title>Gate</title></head><body><h1 id="start">Gate</h1><p>The gate remained closed.</p></body></html>')
(P/'fixtures.json').write_text(json.dumps(cases,ensure_ascii=False,indent=2)+'\n')
print('Prepared',len(cases),'live cases')
